### ISSUE TITLE
[node-ffi] TypeError: error setting argument 0 - valabind [StructType]#set got a bad value

### ISSUE THREAD

**Issue by 3demax** [radare/valabind#22]
I've generated [binding for tox](https://gist.github.com/3demax/9658227), but 

```
/home/user/node-tox-ffi/node_modules/ffi/lib/_foreign_function.js:55
      throw e
            ^
TypeError: error setting argument 0 - valabind [StructType]#set got a bad value
    at Function.set (/home/user/node-tox-ffi/tox_custom.js:65:10)
    at Object.set (/home/user/node-tox-ffi/node_modules/ref/lib/ref.js:479:10)
    at Object.alloc (/home/user/node-tox-ffi/node_modules/ref/lib/ref.js:513:13)
    at ForeignFunction.proxy (/home/user/node-tox-ffi/node_modules/ffi/lib/_foreign_function.js:50:22)
    at StructType.size (/home/user/node-tox-ffi/tox_custom.js:141:13)
    at Object.<anonymous> (/home/user/node-tox-ffi/tox_custom.js:338:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I'm trying to understand this types system, and it's very complicated. 
Can you please explain, what's wrong here?

**Comment by futurepaycc** [comment]
same error

os: linux-x64
vala: 0.50
valabind: 1.7.2 
nodejs: v10.22.1
github.com/antono/vala-object node example (have update node ffi ...)

**Comment by futurepaycc** [comment]
figured out:

nodeffiwriter.vala: 395,397

val.buffer -> val['ref.buffer']

**Comment by trufae** [comment]
Awesome! Can you send a PR? Just pressing the pencil button in github allows you to edit the file and create the pr automatically.

I will setup the CI for further testimg too

Thanks!!
